In [34]:
import numpy as np

import pandas as pd

from numpy.random import randn

np.random.seed(101)


In [35]:
Array = [5]*10
print(Array)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [36]:
import numpy as np

array_of_fives = 5 * np.ones(10)
print(array_of_fives)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [36]:
import numpy as np

array_of_fives = 5 * np.ones(10)
print(array_of_fives)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [37]:
import numpy as np

Array = np.arange(10,51)

print(Array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [38]:
import numpy as np

Array = np.arange(10,51,2)

print(Array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [39]:
import numpy as np

Array = np.arange(0,9).reshape(3,3)

print(Array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [1]:
import numpy as np

Array = np.random.standard_normal(25).reshape(5,5)

print(Array)

[[-1.22675971 -0.91317379 -0.31179394 -0.08332619  0.1452406 ]
 [ 0.77005011  0.15358306  0.42796677  1.45519273  0.02970825]
 [ 0.58337736 -0.01304531 -0.27332788  1.34790766 -0.08793584]
 [ 0.35272235  0.48660302 -1.92683921 -1.08175616 -0.22037008]
 [-1.11635095  0.40711382 -0.45545271  0.93658824  0.30446874]]


In [21]:
import numpy as np

Array = np.arange(0,1.01, 0.01)

print(Array)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [22]:
import numpy as np

Array = np.arange(0,1,0.05)

print(Array)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [ ]:
import numpy as np

Array = np.arange(1,26).reshape(5,5)
print(Array)
print()
slice1 = Array[:3,1:2]

slice2 = Array[2:5,1:5]

print(slice2)
print()
print(slice1)
print()


tsum = np.sum(Array)

rowssum = np.sum(Array, axis = 0)

columnssum = np.sum(Array, axis = 1)

print(tsum)
print()
print(rowssum)
print()
print(columnssum)